version: '3.8'

services:

  machine_learning_client:
    build: ./machineLearningClient
    container_name: machineLearningClient
    image: sst4/machine_learning_client
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - MONGODB_DATABASE=database1
    ports:
      - "6000:6000"
    depends_on:
      - mongodb
    networks:
      - backend

  web-app:
    build: ./web-app
    container_name: web-app
    image: sst4/web-app
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - MONGODB_DATABASE=database1
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - "machine_learning_client"
    networks:
      - backend

  mongodb:
    build: ./mongodb
    container_name: mongodb
    image: sst4/mongodb
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - backend

volumes:
  dbdata:

networks:
  backend: